# ------------ BUILD ------------
FROM node:22-alpine AS build
WORKDIR /usr/src/app

# libs nativas para build (ajuste se precisar de outras)
RUN apk add --no-cache python3 make g++ libc6-compat

# 1) Manifestos primeiro (melhora cache)
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# 2) Copia apenas prisma e gera o client (melhora cache se só o código muda)
COPY prisma ./prisma
RUN yarn prisma generate

# 3) Copia o resto e compila TS -> dist
COPY . .
RUN yarn build


# ------------ RUNTIME ------------
FROM node:22-alpine AS runtime
WORKDIR /usr/src/app

RUN apk add --no-cache wget

# mantenha UMA variável de porta (a mesma do app)
ENV NODE_ENV=production \
    API_PORT=3333

COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/dist        ./dist
COPY --from=build /usr/src/app/package.json ./package.json
COPY --from=build /usr/src/app/prisma       ./prisma

COPY entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

# seu app escuta em 3333
EXPOSE 3333

ENTRYPOINT ["./entrypoint.sh"]
CMD ["node", "--enable-source-maps", "dist/server.js"]
