FROM node:22-alpine

WORKDIR /usr/src/app

RUN apk add --no-cache python3 make g++

COPY package.json yarn.lock ./

RUN yarn install

COPY prisma ./prisma

RUN yarn prisma generate

COPY . .

EXPOSE 3333

CMD ["yarn", "dev"]